import { Role } from '@prisma/client';

const allRoles = {
  [Role.USER]: [
    'getProfile',
    'updateProfile',
    'getPreferences',
    'updatePreferences',
    'getPrivacySettings',
    'updatePrivacySettings',
    'getAccountStatus',
    'getUserStats',
    'getUserActivity',
    'getActivityStats',
    'getUserDevices',
    'getDeviceSessions',
    'trustDevice',
    'removeDevice',
    'removeAllOtherDevices',
    'getUserNotifications',
    'markNotificationAsRead',
    'markAllNotificationsAsRead',
    'deleteNotification',
    'deleteReadNotifications',
    'getNotificationStats',
    'getSecurityLogs',
    'getSecurityStats',
    'exportUserData',
    'deleteAccount',
    'uploadAvatar',
    'removeAvatar',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'regenerateBackupCodes',
    // Inventory & Order Management
    'manageCategories',
    'manageProducts',
    'manageOrders',
    'viewDashboard',
    'viewRestockQueue',
    'restockProducts',
    'viewActivityLog',
  ],
  [Role.ADMIN]: [
    'getUsers',
    'manageUsers',
    'getUserProfile',
    'updateUserProfile',
    'getUserPreferences',
    'updateUserPreferences',
    'getPrivacySettings',
    'updatePrivacySettings',
    'getAccountStatus',
    'getUserStats',
    'getUserActivity',
    'getActivityStats',
    'getUserDevices',
    'getDeviceSessions',
    'trustDevice',
    'removeDevice',
    'removeAllOtherDevices',
    'getUserNotifications',
    'markNotificationAsRead',
    'markAllNotificationsAsRead',
    'deleteNotification',
    'deleteReadNotifications',
    'getNotificationStats',
    'getSecurityLogs',
    'getSecurityStats',
    'exportUserData',
    'deleteAccount',
    'uploadAvatar',
    'removeAvatar',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'regenerateBackupCodes',
    'getUsersWithExpiringPasswords',
    'getLockedUsers',
    'unlockUserAccount',
    'forcePasswordChange',
    'getDetailedHealthCheck',
    // Inventory & Order Management
    'manageCategories',
    'manageProducts',
    'manageOrders',
    'viewDashboard',
    'viewRestockQueue',
    'restockProducts',
    'viewActivityLog',
    'deleteCategory',
    'deleteProduct',
    'deleteOrder',
  ],
};

export const roles = Object.keys(allRoles);
export const roleRights = new Map(Object.entries(allRoles));

// Export roles object for use in routes
export { Role };
